apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: archaics

resources:
  - namespace.yaml
  - auth
  - db
  - product
  - payment
  - ai-operator
  - anomaly-detector

secretGenerator:
  - name: archaics-secrets
    literals:
      - JWT_SECRET=archaIc-secret-key-2024
      - STRIPE_API_KEY=sk_test_dummy
  - name: ai-operator-secrets
    envs:
      - ../../../.env

generatorOptions:
  disableNameSuffixHash: true
